kind: PersistentVolume
apiVersion: v1
metadata:
  name: nexus-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 8.8Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/nexus"
