kind: PersistentVolume
apiVersion: v1
metadata:
  name: sonar-postgres-pvc
  namespace: sonar
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/Volumes/data"
