apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonar-postgres-pvc-claim
  namespace: sonar
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
