kind: PersistentVolume
apiVersion: v1
metadata:
  name: jenkins-leader-pv
  namespace: jenkins
  labels:
    app: jenkins-leader
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
